spring:
  application:
    name: kafkaproducerhomework
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_app
    username: postgres_user
    password: 123
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:29093
topic-to-send-message: topic1
management:
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      service: "user-service"
  endpoints:
    web:
      base-path: /admin/actuator
      exposure:
        include: health, info, prometheus, metrics
        exclude: shutdown
logging:
  level:
    com.example.kafkaproducerhomework.service: DEBUG
    com.example.kafkaproducerhomework.repository: DEBUG
    com.example.kafkaproducerhomework.scheduler: DEBUG
    org.flywaydb: DEBUG