spring:
  application:
    name: kafkaproducerhomework
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_app
    username: postgres_user
    password: 123
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:29093
topic-to-send-message: topic1
logging:
  level:
    com.example.kafkaproducerhomework.service: DEBUG
    com.example.kafkaproducerhomework.repository: DEBUG
    org.flywaydb: DEBUG